// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package sample

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func Wire() (*handler, error) {
	sampleRepository := repository{}
	sampleService := service{
		repo: sampleRepository,
	}
	sampleHandler := &handler{
		svc: sampleService,
	}
	return sampleHandler, nil
}

func WireService() (*service, error) {
	sampleRepository := repository{}
	sampleService := &service{
		repo: sampleRepository,
	}
	return sampleService, nil
}

func WireRepository() (*repository, error) {
	sampleRepository := &repository{}
	return sampleRepository, nil
}

// wire.go:

var ProviderSet = wire.NewSet(wire.Struct(new(handler), "*"), wire.Struct(new(service), "*"), wire.Struct(new(repository)))
