// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package sample

import (
	"github.com/google/wire"
	"golang-job-frame/domain/sample"
)

// Injectors from wire.go:

func Wire() *handler {
	sampleRepository := ProviderRepository()
	sampleService := ProviderService(sampleRepository)
	sampleHandler := ProviderHandler(sampleService)
	return sampleHandler
}

// wire.go:

var ProviderSet = wire.NewSet(
	ProviderHandler,
	ProviderService,
	ProviderRepository, wire.Bind(new(domain.SampleHandler), new(*handler)), wire.Bind(new(domain.SampleService), new(*service)), wire.Bind(new(domain.SampleRepository), new(*repository)),
)
