// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"golang-job-frame/domain/sample"
	"golang-job-frame/pkg/sample"
)

// Injectors from wire.go:

func Wire() (*sample.Handler, error) {
	repository := sample.ProviderRepository()
	service := sample.ProviderService(repository)
	handler := sample.ProviderHandler(service)
	return handler, nil
}

func WireService() (*sample.Service, error) {
	repository := sample.ProviderRepository()
	service := sample.ProviderService(repository)
	return service, nil
}

// wire.go:

var ProviderSet = wire.NewSet(sample.ProviderHandler, sample.ProviderService, sample.ProviderRepository, wire.Bind(new(domain.SampleHandler), new(*sample.Handler)), wire.Bind(new(domain.SampleService), new(*sample.Service)), wire.Bind(new(domain.SampleRepository), new(*sample.Repository)))
